services:
  - type: web
    name: Tree Of Us
    env: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile db:assets:clean
    preDeployCommand: bundle exec rails db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0