# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '08bd1f726b464fd36d8398301ca86ec2'
  config.secret_key = 'bf38b9fa92c008eccb192573d3958f57'
  config.default_from = 'maria.usama9211@gmail.com'
  config.api_version = 'v3.1'
end
